-- liquibase formatted sql

--changeset andrey:111
-- Создание таблицы "users" для хранения информации о пользователях
CREATE TABLE users(
    id  BIGINT generated by default as identity primary key, -- Уникальный идентификатор пользователя
    telegram_id   BIGINT   NOT NULL, -- Идентификатор пользователя в Telegram
    name    TEXT, -- Имя пользователя
    phone_number  TEXT, -- Номер телефона пользователя
    car_number    TEXT, -- Номер автомобиля пользователя
    city    TEXT -- Город проживания пользователя
);

-- Создание таблицы "animals" для хранения информации о животных
CREATE TABLE animals(
    id        BIGINT generated by default as identity primary key, -- Уникальный идентификатор животного
    name TEXT     NOT NULL, -- Имя животного
    pet_type  SMALLINT NOT NULL, -- Тип животного (например, кошка, собака и т. д.)
    color     SMALLINT NOT NULL, -- Цвет животного
    sex       SMALLINT NOT NULL -- Пол животного (например, самец, самка)
);

-- Создание таблицы "adopters" для хранения информации о приемных родителях животных
CREATE TABLE adopters(
    id         BIGINT generated by default as identity primary key, -- Уникальный идентификатор приемного родителя
    user_id    BIGINT, -- Идентификатор пользователя
    animal_id  BIGINT NOT NULL, -- Идентификатор животного
    shelter_id BIGINT NOT NULL -- Идентификатор приюта
);